/* Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact__region0_Avanzar(Statechart* handle);
static void enact__region0_Izq(Statechart* handle);
static void enact__region0_Der(Statechart* handle);
static void enseq__region0_Avanzar_default(Statechart* handle);
static void enseq__region0_Izq_default(Statechart* handle);
static void enseq__region0_Der_default(Statechart* handle);
static void enseq__region0_default(Statechart* handle);
static void exseq__region0_Avanzar(Statechart* handle);
static void exseq__region0_Izq(Statechart* handle);
static void exseq__region0_Der(Statechart* handle);
static void exseq__region0(Statechart* handle);
static void react__region0__entry_Default(Statechart* handle);

/*! The reactions of state Avanzar. */
static sc_integer _region0_Avanzar_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Izq. */
static sc_integer _region0_Izq_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Der. */
static sc_integer _region0_Der_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);






static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq__region0_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq__region0(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart__region0_Avanzar :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART__REGION0_AVANZAR] == Statechart__region0_Avanzar
			);
				break;
		case Statechart__region0_Izq :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART__REGION0_IZQ] == Statechart__region0_Izq
			);
				break;
		case Statechart__region0_Der :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART__REGION0_DER] == Statechart__region0_Der
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->ifaceSensores.sensor_D_1_raised = bool_false;
	handle->ifaceSensores.sensor_D_0_raised = bool_false;
	handle->ifaceSensores.sensor_I_1_raised = bool_false;
	handle->ifaceSensores.sensor_I_0_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart__region0_Avanzar :
		{
			_region0_Avanzar_react(handle,-1);
			break;
		}
		case Statechart__region0_Izq :
		{
			_region0_Izq_react(handle,-1);
			break;
		}
		case Statechart__region0_Der :
		{
			_region0_Der_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_sensores_raise_sensor_D_1(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensores_sensor_D_1);
	run_cycle(handle);
}

void statechart_sensores_raise_sensor_D_0(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensores_sensor_D_0);
	run_cycle(handle);
}

void statechart_sensores_raise_sensor_I_1(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensores_sensor_I_1);
	run_cycle(handle);
}

void statechart_sensores_raise_sensor_I_0(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensores_sensor_I_0);
	run_cycle(handle);
}








/* implementations of all internal functions */

/* Entry action for state 'Avanzar'. */
static void enact__region0_Avanzar(Statechart* handle)
{
	/* Entry action for state 'Avanzar'. */
	statechart_acciones_avanzar(handle);
}

/* Entry action for state 'Izq'. */
static void enact__region0_Izq(Statechart* handle)
{
	/* Entry action for state 'Izq'. */
	statechart_acciones_doblar_izq(handle);
}

/* Entry action for state 'Der'. */
static void enact__region0_Der(Statechart* handle)
{
	/* Entry action for state 'Der'. */
	statechart_acciones_doblar_der(handle);
}

/* 'default' enter sequence for state Avanzar */
static void enseq__region0_Avanzar_default(Statechart* handle)
{
	/* 'default' enter sequence for state Avanzar */
	enact__region0_Avanzar(handle);
	handle->stateConfVector[0] = Statechart__region0_Avanzar;
}

/* 'default' enter sequence for state Izq */
static void enseq__region0_Izq_default(Statechart* handle)
{
	/* 'default' enter sequence for state Izq */
	enact__region0_Izq(handle);
	handle->stateConfVector[0] = Statechart__region0_Izq;
}

/* 'default' enter sequence for state Der */
static void enseq__region0_Der_default(Statechart* handle)
{
	/* 'default' enter sequence for state Der */
	enact__region0_Der(handle);
	handle->stateConfVector[0] = Statechart__region0_Der;
}

/* 'default' enter sequence for region  */
static void enseq__region0_default(Statechart* handle)
{
	/* 'default' enter sequence for region  */
	react__region0__entry_Default(handle);
}

/* Default exit sequence for state Avanzar */
static void exseq__region0_Avanzar(Statechart* handle)
{
	/* Default exit sequence for state Avanzar */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Izq */
static void exseq__region0_Izq(Statechart* handle)
{
	/* Default exit sequence for state Izq */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Der */
static void exseq__region0_Der(Statechart* handle)
{
	/* Default exit sequence for state Der */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region  */
static void exseq__region0(Statechart* handle)
{
	/* Default exit sequence for region  */
	/* Handle exit of all possible states (of Statechart._region0) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart__region0_Avanzar :
		{
			exseq__region0_Avanzar(handle);
			break;
		}
		case Statechart__region0_Izq :
		{
			exseq__region0_Izq(handle);
			break;
		}
		case Statechart__region0_Der :
		{
			exseq__region0_Der(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react__region0__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq__region0_Avanzar_default(handle);
}


static sc_integer _region0_Avanzar_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Avanzar. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceSensores.sensor_I_1_raised == bool_true)
		{ 
			exseq__region0_Avanzar(handle);
			enseq__region0_Der_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (handle->ifaceSensores.sensor_D_1_raised == bool_true)
			{ 
				exseq__region0_Avanzar(handle);
				enseq__region0_Izq_default(handle);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer _region0_Izq_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Izq. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceSensores.sensor_D_0_raised == bool_true)
		{ 
			exseq__region0_Izq(handle);
			enseq__region0_Avanzar_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer _region0_Der_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Der. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceSensores.sensor_I_0_raised == bool_true)
		{ 
			exseq__region0_Der(handle);
			enseq__region0_Avanzar_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_sensores_sensor_D_1:
		{
			handle->ifaceSensores.sensor_D_1_raised = bool_true;
			return bool_true;
		}
		case Statechart_sensores_sensor_D_0:
		{
			handle->ifaceSensores.sensor_D_0_raised = bool_true;
			return bool_true;
		}
		case Statechart_sensores_sensor_I_1:
		{
			handle->ifaceSensores.sensor_I_1_raised = bool_true;
			return bool_true;
		}
		case Statechart_sensores_sensor_I_0:
		{
			handle->ifaceSensores.sensor_I_0_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
